[PAN-2831]: Add info about filters being subscriptions
PegaSysEng/doc.pantheon pull request #20
Opened 2019-08-27 16:51 UTC by sgregglives

## PR description

This fix adds content in several topics that clarifies the alternatives for subscriptions.

## Fixed Issue(s)

PAN-2831

2019-08-28 18:28 UTC, NicolasMassart requested changes
just an issue with aa change in Privacy-Groups.md that should not be there otherwise looks good to me. I will approve once the change done and merge conflict fixed.

2019-08-28 18:28 UTC, NicolasMassart commented on docs/Privacy/Explanation/Privacy-Groups.md
> +Contracts have the following levels of access between public and private states:
It looks like PAN-2831 is not about privacy so this change me be a mistake in this PR.

2019-08-29 05:45 UTC, MadelineMurray approved these changes

2019-08-29 05:45 UTC, MadelineMurray commented on docs/Pantheon-API/RPC-PubSub.md
> +You can subscribe to events by using either RPC Pub/Sub over WebSockets or [filters over HTTP](../Using-Pantheon/Accessing-Logs-Using-JSON-RPC.md).
Suggestion only - this could be rewritten more actively as: 
Subscribe to event using either ....

2019-08-29 05:45 UTC, MadelineMurray commented on docs/Using-Pantheon/Accessing-Logs-Using-JSON-RPC.md
> +You can subscribe to events, such as logs, by using either [RPC Pub/Sub over WebSockets](../Pantheon-API/RPC-PubSub.md) or filters over HTTP.
Similar comment to above: 
Subscribe to events, such as logs, using either filters over HTTP or RPC Pub/Sub....

2019-08-29 15:47 UTC, sgregglives commented
I created another branch from master.

2019-08-29 15:47 UTC, closed without merging